[INFO] [1750160678.160170581] [laser_data_loader]: モデルの読み込みが完了しました。
[INFO] [1750160678.160546522] [laser_data_loader]: 初期化完了。推論待機中です...
[ERROR] [1750160679.309352063] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160679.410347616] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160679.509951942] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160679.610495698] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160679.713152699] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160679.807148339] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160679.907131887] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160680.007093778] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160680.105048747] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160680.212965537] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160680.316695306] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160680.408306807] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160680.513950283] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160680.607152313] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160680.708116428] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160680.813919900] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160680.909933528] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160681.010029892] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160681.113250076] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160681.214044024] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160681.314045405] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
[ERROR] [1750160681.410414849] [laser_data_loader]: PointCloudのパースに失敗: 'array.array' object has no attribute 'fields'
